if ('serviceWorker' in navigator) { navigator.serviceWorker.register('sw.js').catch(()=>{}); }
const FILE_SYSTEM = {"Ce PC": {"Disque Local (C:)": {icon:"💾"}, "Disque Data (D:)": {icon:"🗄️"}, "Clé USB (E:)": {icon:"🔑"}}};
let zIndexCounter=10, currentPath="Ce PC";
let userFolders, importedFiles;
try{ userFolders=JSON.parse(localStorage.getItem('asamoi_folders')||'null')||['Documents','Chantier Carena','Projets Web']; importedFiles=JSON.parse(localStorage.getItem('asamoi_files')||'null')||[]; }catch(e){ userFolders=['Documents','Chantier Carena','Projets Web']; importedFiles=[]; }
setInterval(()=>{ const el=document.getElementById('clock'); if(el) el.innerText=new Date().toLocaleTimeString('fr-FR'); },1000);
function openWindow(id){ const w=document.getElementById(id); if(!w) return; w.classList.add('active'); w.style.zIndex=++zIndexCounter; closeStartMenu(); if(id==='win-explorer') renderExplorer(currentPath); makeDraggable(w); }
function closeWindow(id){ document.getElementById(id)?.classList.remove('active'); }
function minimizeWindow(id){ closeWindow(id); }
function makeDraggable(win){ const h=win.querySelector('.window-header'); if(!h||h.dataset.drag==="1") return; h.dataset.drag="1"; let sx,sy,ox,oy,drag=false; const s=(x,y)=>{drag=true;sx=x;sy=y;ox=win.offsetLeft;oy=win.offsetTop;win.style.zIndex=++zIndexCounter;}; const m=(x,y)=>{if(!drag) return; win.style.left=(ox+x-sx)+'px'; win.style.top=(oy+y-sy)+'px';}; const e=()=>drag=false; h.addEventListener('touchstart',ev=>s(ev.touches[0].clientX,ev.touches[0].clientY),{passive:false}); h.addEventListener('touchmove',ev=>{ev.preventDefault(); m(ev.touches[0].clientX,ev.touches[0].clientY);},{passive:false}); h.addEventListener('touchend',e); h.addEventListener('mousedown',ev=>{s(ev.clientX,ev.clientY); const mm=e=>m(e.clientX,e.clientY); const mu=()=>{e();document.removeEventListener('mousemove',mm);document.removeEventListener('mouseup',mu);}; document.addEventListener('mousemove',mm); document.addEventListener('mouseup',mu);}); }
function toggleStartMenu(){ const m=document.getElementById('start-menu'); m.classList.toggle('start-menu-hidden'); if(!m.classList.contains('start-menu-hidden')) document.getElementById('startSearchInput')?.focus(); }
function closeStartMenu(){ document.getElementById('start-menu')?.classList.add('start-menu-hidden'); }
function launchFromStart(id){ openWindow(id); }
function filterStartMenu(e){ if(e.key!=='Enter') return; const q=document.getElementById('startSearchInput').value.toLowerCase(); if(q.includes('cmd')) openWindow('win-cmd'); else if(q.includes('word')) openWindow('win-word'); else if(q.includes('chrome')||q.includes('navigateur')||q.includes('google')||q.includes('youtube')) openWindow('win-browser'); else if(q.includes('aide')||q.includes('code')) openWindow('win-help'); else openWindow('win-explorer'); }
function renderExplorer(path="Ce PC"){ currentPath=path; const list=document.getElementById('explorer-files-list'); const bc=document.getElementById('explorer-path'); if(!list) return; if(bc) bc.innerText=path; list.innerHTML=""; if(path==="Ce PC"){ Object.entries(FILE_SYSTEM["Ce PC"]).forEach(([name,drive])=>{ list.innerHTML+=`<div class="drive-item" onclick="renderExplorer('${name}')" style="display:flex;align-items:center;gap:12px;padding:14px;border-bottom:1px solid #eee;cursor:pointer;"><span style="font-size:30px">${drive.icon}</span><div><b>${name}</b><br><small style="color:#666">120 Go libre sur 250 Go</small><div style="background:#ddd;height:6px;width:140px;margin-top:5px;border-radius:3px"><div style="background:#0078d7;width:55%;height:100%;border-radius:3px"></div></div></div></div>`; }); return; } list.innerHTML=`<div onclick="renderExplorer('Ce PC')" style="cursor:pointer;color:#0078d7;margin-bottom:12px;font-weight:600;padding:10px">⬅️ Retour à Ce PC</div>`; userFolders.forEach(f=>{list.innerHTML+=`<div style="padding:8px 10px;">📁 ${f}</div>`;}); if(importedFiles.length===0){list.innerHTML+=`<p style="color:#777;margin:12px 10px;font-size:13px;">Aucun fichier dans ${path}. Clique sur + Importer.</p>`;} importedFiles.forEach((file,i)=>{list.innerHTML+=`<div style="display:flex;justify-content:space-between;align-items:center;padding:10px;border-bottom:1px solid #f5f5f5;"><span>📄 ${file.name}</span><div><button onclick="openImportedFile(${i})" style="background:#0078d7;color:#fff;border:none;padding:5px 10px;border-radius:5px;margin-right:6px;">Ouvrir</button><button onclick="deleteImportedFile(${i})" style="background:#e81123;color:#fff;border:none;padding:5px 9px;border-radius:5px;">X</button></div></div>`;}); }
function navigateTo(url){
  if(!url.startsWith('http')) url='https://'+url;
  document.getElementById('browser-url').value=url;
  const preview=document.getElementById('browser-preview');
  const iframe=document.getElementById('browser-iframe');
  if(preview) preview.style.display='block';
  if(iframe) iframe.src=url;
  setTimeout(()=>{ window.open(url,'_blank'); }, 700);
}
function browserGo(){
  let url=document.getElementById('browser-url').value.trim();
  if(!url) return;
  navigateTo(url);
}
function renderFolders(){ const c=document.getElementById('folders-container'); if(!c) return; c.innerHTML=`<div class="icon" onclick="renderExplorer('Ce PC'); openWindow('win-explorer')"><span>🖥️</span><p>Ce PC</p></div><div class="icon" onclick="openWindow('win-browser')"><span>🌐</span><p>Chrome</p></div><div class="icon" onclick="openWindow('win-word')"><span>📝</span><p>WordPad</p></div><div class="icon" onclick="openWindow('win-cmd')"><span>⌨️</span><p>CMD</p></div><div class="icon" onclick="openWindow('win-help')"><span>❓</span><p>Aide</p></div>${userFolders.map(f=>`<div class="icon"><span>📁</span><p>${f}</p></div>`).join('')}${importedFiles.map((f,i)=>`<div class="icon" onclick="openImportedFile(${i})"><span>📄</span><p style="font-size:11px;overflow:hidden;white-space:nowrap;width:75px">${f.name}</p></div>`).join('')}`; }
function importFileToOS(e){ const file=e.target.files[0]; if(!file) return; const r=new FileReader(); r.onload=ev=>{ importedFiles.push({name:file.name,size:(file.size/1024).toFixed(1)+' Ko',content:ev.target.result}); localStorage.setItem('asamoi_files',JSON.stringify(importedFiles)); renderFolders(); renderExplorer(currentPath); }; r.readAsDataURL(file); }
function openImportedFile(i){ const f=importedFiles[i]; if(!f) return; const w=window.open('','_blank'); if(f.content.startsWith('data:image')){ w.document.write(`<img src="${f.content}" style="max-width:100%">`);} else { w.document.write(`<pre style="padding:20px">${f.name}</pre>`);} }
function deleteImportedFile(i){ if(confirm("Supprimer?")){ importedFiles.splice(i,1); localStorage.setItem('asamoi_files',JSON.stringify(importedFiles)); renderFolders(); renderExplorer(currentPath);} }
function systemAction(a){ if(a==='shutdown'){ document.getElementById('shutdown-screen').style.display='flex'; closeStartMenu(); } else if(a==='restart'){ location.reload(); } }
function turnOnPC(){ document.getElementById('shutdown-screen').style.display='none'; }
function toggleVirtualKeyboard(){ const kb=document.getElementById('virtual-keyboard'); if(!kb) return; kb.style.display=kb.style.display==='flex'?'none':'flex'; }
function sendKey(k){ const el=document.activeElement; if(!el) return; if(el.tagName==='INPUT'||el.tagName==='TEXTAREA'){ if(k==='BACKSPACE') el.value=el.value.slice(0,-1); else if(k==='Tab') el.value+='\t'; else el.value+=k; } else if(el.isContentEditable){ if(k==='BACKSPACE') document.execCommand('delete',false,null); else document.execCommand('insertText',false,k);} }
function handleCmd(e){ if(e.key==='Enter'){ const inp=document.getElementById('cmd-input'); const out=document.getElementById('cmd-output'); const raw=inp.value; const val=raw.trim().toLowerCase(); out.innerHTML+=`C:\\Users\\Admin> ${raw}<br>`; if(val==='help') out.innerHTML+=`help, cls, date, ver, shutdown, explorer, chrome, word<br><br>`; else if(val==='cls') out.innerHTML=''; else if(val==='date') out.innerHTML+=`${new Date().toLocaleString()}<br><br>`; else if(val==='ver') out.innerHTML+=`AsaMoi OS [Version 11.0]<br><br>`; else if(val==='explorer') openWindow('win-explorer'); else if(val==='chrome') openWindow('win-browser'); else if(val==='word') openWindow('win-word'); else if(val==='shutdown') systemAction('shutdown'); else if(val!=='') out.innerHTML+=`'${val}' non reconnu.<br><br>`; inp.value=''; out.scrollTop=out.scrollHeight; } }
function filterCheatSheet(){ const q=document.getElementById('searchCheat')?.value.toLowerCase()||''; document.querySelectorAll('.cheat-sheet-section').forEach(s=>{ s.style.display=s.innerText.toLowerCase().includes(q)?'block':'none'; }); }
window.addEventListener('DOMContentLoaded', renderFolders);
window.addEventListener('click', e=>{ if(!e.target.closest('#start-menu') &&!e.target.closest('#start-btn')) closeStartMenu(); });
